[tool.kedro]
package_name = "kedro_python"
project_name = "kedro_mlflow_project"
kedro_init_version = "0.18.9"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/kedro_python -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
